name: Publish to Docker Hub

on:
  push:
    branches:
      - master # 触发工作流的分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t huihuidehui/ptbrush:${{ github.sha }} .
          docker tag huihuidehui/ptbrush:${{ github.sha }} huihuidehui/ptbrush:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push huihuidehui/ptbrush:latest
          docker push huihuidehui/ptbrush:${{ github.sha }}